# Generated by Django 4.2 on 2023-04-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
