# Generated by Django 4.2 on 2023-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
